In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("data/retail-store-inventory.csv", parse_dates=["Date"])

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                73100 non-null  datetime64[ns]
 1   Store ID            73100 non-null  object
 2   Product ID          73100 non-null  object
 3   Category            73100 non-null  object
 4   Region              73100 non-null  object
 5   Inventory Level     73100 non-null  int64
 6   Units Sold          73100 non-null  int64
 7   Units Ordered       73100 non-null  int64
 8   Demand Forecast     73100 non-null  float64
 9   Price               73100 non-null  float64
 10  Discount            73100 non-null  int64
 11  Weather Condition   73100 non-null  object
 12  Holiday/Promotion   73100 non-null  int64
 13  Competitor Pricing  73100 non-null  float64
 14  Seasonality         73100 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(5), object(6)
memory usage: 8.4+ MB

In [4]:
# sorting values for consistency
df = df.sort_values(["Store ID", "Product ID", "Date"])

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 73100 entries, 0 to 73099
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                73100 non-null  datetime64[ns]
 1   Store ID            73100 non-null  object
 2   Product ID          73100 non-null  object
 3   Category            73100 non-null  object
 4   Region              73100 non-null  object
 5   Inventory Level     73100 non-null  int64
 6   Units Sold          73100 non-null  int64
 7   Units Ordered       73100 non-null  int64
 8   Demand Forecast     73100 non-null  float64
 9   Price               73100 non-null  float64
 10  Discount            73100 non-null  int64
 11  Weather Condition   73100 non-null  object
 12  Holiday/Promotion   73100 non-null  int64
 13  Competitor Pricing  73100 non-null  float64
 14  Seasonality         73100 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(5), object(6)
memory usage: 8.9+ MB

In [6]:
df_temp = df.copy()

In [7]:
# converting the date into numerical features
df_temp["saleYear"] = df_temp.Date.dt.year
df_temp["saleMonth"] = df_temp.Date.dt.month
df_temp["saleDay"] = df_temp.Date.dt.day
df_temp["dayOfWeek"] = df_temp.Date.dt.dayofweek
df_temp["dayOfYear"] = df_temp.Date.dt.dayofyear

In [8]:
df_temp = df_temp.drop("Date", axis=1)

In [9]:
df_temp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 73100 entries, 0 to 73099
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Store ID            73100 non-null  object
 1   Product ID          73100 non-null  object
 2   Category            73100 non-null  object
 3   Region              73100 non-null  object
 4   Inventory Level     73100 non-null  int64
 5   Units Sold          73100 non-null  int64
 6   Units Ordered       73100 non-null  int64
 7   Demand Forecast     73100 non-null  float64
 8   Price               73100 non-null  float64
 9   Discount            73100 non-null  int64
 10  Weather Condition   73100 non-null  object
 11  Holiday/Promotion   73100 non-null  int64
 12  Competitor Pricing  73100 non-null  float64
 13  Seasonality         73100 non-null  object
 14  saleYear            73100 non-null  int32
 15  saleMonth           73100 non-null  int32
 16  saleDay             73100 non-null  int32
 17  dayOfWeek           73100 non-null  int32
 18  dayOfYear           73100 non-null  int32
dtypes: float64(3), int32(5), int64(5), object(6)
memory usage: 9.8+ MB

In [11]:
# printing the columns which are not in numerical format
for label, content in df_temp.items():
    if not pd.api.types.is_numeric_dtype(content):
        print(label)

Store ID
Product ID
Category
Region
Weather Condition
Seasonality

In [12]:
# converting the columns to numerical type by changing them into the categorical data type
for label, content in df_temp.items():
    if not pd.api.types.is_numeric_dtype(content):
        df_temp[label] = content.astype("category").cat.as_ordered()

In [39]:
df_temp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 73100 entries, 0 to 73099
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Store ID            73100 non-null  category
 1   Product ID          73100 non-null  category
 2   Category            73100 non-null  category
 3   Region              73100 non-null  category
 4   Inventory Level     73100 non-null  int64
 5   Units Sold          73100 non-null  int64
 6   Units Ordered       73100 non-null  int64
 7   Demand Forecast     73100 non-null  float64
 8   Price               73100 non-null  float64
 9   Discount            73100 non-null  int64
 10  Weather Condition   73100 non-null  category
 11  Holiday/Promotion   73100 non-null  int64
 12  Competitor Pricing  73100 non-null  float64
 13  Seasonality         73100 non-null  category
 14  saleYear            73100 non-null  int32
 15  saleMonth           73100 non-null  int32
 16  saleDay             73100 non-null  int32
 17  dayOfWeek           73100 non-null  int32
 18  dayOfYear           73100 non-null  int32
dtypes: category(6), float64(3), int32(5), int64(5)
memory usage: 6.8 MB

In [13]:
df_temp.isnull().sum()

Store ID              0
Product ID            0
Category              0
Region                0
Inventory Level       0
Units Sold            0
Units Ordered         0
Demand Forecast       0
Price                 0
Discount              0
Weather Condition     0
Holiday/Promotion     0
Competitor Pricing    0
Seasonality           0
saleYear              0
saleMonth             0
saleDay               0
dayOfWeek             0
dayOfYear             0
dtype: int64

there is no missing data, so we can jump into the modelling phase

In [19]:
df_temp.head(20)

,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality,saleYear,saleMonth,saleDay,dayOfWeek,dayOfYear
0,S001,P0001,Groceries,North,231,127,55,135.47,33.50,20,Rainy,0,29.69,Autumn,2022,1,1,5,1
100,S001,P0001,Groceries,West,116,81,104,92.94,27.95,10,Cloudy,0,30.89,Spring,2022,1,2,6,2
200,S001,P0001,Electronics,West,154,5,189,5.36,62.70,20,Rainy,0,58.22,Winter,2022,1,3,0,3
300,S001,P0001,Groceries,South,85,58,193,52.87,77.88,15,Cloudy,1,75.99,Winter,2022,1,4,1,4
400,S001,P0001,Groceries,South,238,147,37,150.27,28.46,20,Sunny,1,29.40,Winter,2022,1,5,2,5
500,S001,P0001,Electronics,East,198,37,155,39.09,91.05,5,Snowy,0,87.30,Summer,2022,1,6,3,6
600,S001,P0001,Furniture,North,195,107,106,117.92,53.99,10,Sunny,1,58.80,Winter,2022,1,7,4,7
700,S001,P0001,Furniture,East,231,2,119,0.84,66.30,20,Cloudy,1,63.82,Winter,2022,1,8,5,8
800,S001,P0001,Electronics,South,373,350,178,352.24,41.72,0,Sunny,1,38.68,Summer,2022,1,9,6,9
900,S001,P0001,Electronics,West,327,36,132,39.50,32.68,5,Snowy,1,34.71,Summer,2022,1,10,0,10
1000,S001,P0001,Furniture,West,101,16,193,16.11,27.53,5,Rainy,1,27.08,Autumn,2022,1,11,1,11
1100,S001,P0001,Toys,South,145,104,189,100.32,92.92,0,Snowy,0,97.59,Winter,2022,1,12,2,12
1200,S001,P0001,Furniture,East,110,80,190,78.64,17.27,15,Snowy,1,21.79,Spring,2022,1,13,3,13
1300,S001,P0001,Toys,North,199,177,44,193.23,90.05,20,Snowy,0,87.05,Winter,2022,1,14,4,14
1400,S001,P0001,Groceries,North,290,176,94,170.06,98.04,10,Rainy,1,98.20,Spring,2022,1,15,5,15
1500,S001,P0001,Groceries,East,104,97,189,114.65,11.39,15,Snowy,0,7.96,Winter,2022,1,16,6,16
1600,S001,P0001,Groceries,East,134,69,95,73.59,95.27,0,Rainy,1,92.60,Summer,2022,1,17,0,17
1700,S001,P0001,Electronics,North,339,123,157,134.00,90.70,15,Sunny,0,86.51,Spring,2022,1,18,1,18
1800,S001,P0001,Groceries,West,431,211,139,228.92,97.97,10,Cloudy,0,95.06,Summer,2022,1,19,2,19
1900,S001,P0001,Furniture,North,154,79,113,90.49,10.38,0,Cloudy,0,11.46,Spring,2022,1,20,3,20

In [20]:
df_temp.tail(20)

,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality,saleYear,saleMonth,saleDay,dayOfWeek,dayOfYear
71199,S005,P0020,Toys,West,51,12,112,29.90,21.84,15,Sunny,1,26.79,Spring,2023,12,13,2,347
71299,S005,P0020,Clothing,South,110,80,77,81.46,57.43,20,Sunny,0,52.58,Winter,2023,12,14,3,348
71399,S005,P0020,Clothing,North,288,280,118,290.06,14.26,20,Cloudy,0,16.64,Spring,2023,12,15,4,349
71499,S005,P0020,Furniture,West,81,3,67,-5.79,28.33,15,Sunny,1,25.72,Summer,2023,12,16,5,350
71599,S005,P0020,Clothing,South,348,165,198,164.94,24.28,5,Rainy,1,25.96,Spring,2023,12,17,6,351
71699,S005,P0020,Electronics,North,397,113,98,107.69,40.82,15,Rainy,0,37.05,Spring,2023,12,18,0,352
71799,S005,P0020,Electronics,West,285,253,152,247.26,19.46,0,Snowy,0,20.93,Summer,2023,12,19,1,353
71899,S005,P0020,Electronics,West,192,91,72,96.67,90.24,15,Sunny,1,89.45,Spring,2023,12,20,2,354
71999,S005,P0020,Furniture,West,281,160,128,162.11,58.88,15,Rainy,0,57.27,Autumn,2023,12,21,3,355
72099,S005,P0020,Furniture,North,371,228,117,223.15,87.83,20,Rainy,0,88.54,Winter,2023,12,22,4,356
72199,S005,P0020,Toys,East,471,220,123,218.73,96.80,10,Sunny,1,99.42,Winter,2023,12,23,5,357
72299,S005,P0020,Furniture,South,430,6,31,22.37,12.23,5,Sunny,1,11.16,Summer,2023,12,24,6,358
72399,S005,P0020,Furniture,South,322,31,187,46.54,26.51,0,Snowy,1,29.40,Spring,2023,12,25,0,359
72499,S005,P0020,Clothing,North,288,153,81,164.99,88.45,0,Cloudy,1,84.35,Autumn,2023,12,26,1,360
72599,S005,P0020,Toys,West,144,138,109,128.95,17.53,0,Cloudy,0,16.63,Autumn,2023,12,27,2,361
72699,S005,P0020,Groceries,South,198,56,27,50.18,21.75,5,Sunny,1,25.29,Winter,2023,12,28,3,362
72799,S005,P0020,Clothing,East,446,268,30,267.54,85.58,20,Sunny,1,87.63,Summer,2023,12,29,4,363
72899,S005,P0020,Toys,North,251,149,181,162.92,79.48,10,Cloudy,1,82.69,Autumn,2023,12,30,5,364
72999,S005,P0020,Furniture,East,64,40,99,59.69,90.79,5,Snowy,1,91.67,Winter,2023,12,31,6,365
73099,S005,P0020,Groceries,East,117,6,165,2.33,78.39,20,Rainy,1,79.52,Spring,2024,1,1,0,1

In [36]:
df_temp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 73100 entries, 0 to 73099
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Store ID            73100 non-null  category
 1   Product ID          73100 non-null  category
 2   Category            73100 non-null  category
 3   Region              73100 non-null  category
 4   Inventory Level     73100 non-null  int64
 5   Units Sold          73100 non-null  int64
 6   Units Ordered       73100 non-null  int64
 7   Demand Forecast     73100 non-null  float64
 8   Price               73100 non-null  float64
 9   Discount            73100 non-null  int64
 10  Weather Condition   73100 non-null  category
 11  Holiday/Promotion   73100 non-null  int64
 12  Competitor Pricing  73100 non-null  float64
 13  Seasonality         73100 non-null  category
 14  saleYear            73100 non-null  int32
 15  saleMonth           73100 non-null  int32
 16  saleDay             73100 non-null  int32
 17  dayOfWeek           73100 non-null  int32
 18  dayOfYear           73100 non-null  int32
 19  FullDate            73100 non-null  datetime64[ns]
dtypes: category(6), datetime64[ns](1), float64(3), int32(5), int64(5)
memory usage: 7.4 MB

In [26]:
# Combine the date components into a single datetime column
# A new 'FullDate' column has been created for this purpose
df_temp['FullDate'] = pd.to_datetime(
    df_temp[['saleYear', 'saleMonth', 'saleDay']].rename(
        columns={'saleYear': 'year', 'saleMonth': 'month', 'saleDay': 'day'}
    )
)

In [27]:
SPLIT_DATE = pd.to_datetime('2023-10-01')

Here we are going to split the data into 80:20 ratio. The process is slightly different since we are dealing with time-series data, meaning that there is a chronological order that we cannot randomly pick from.

In [38]:
# Create the training set: all data before the split date
train_df = df_temp[df_temp['FullDate'] < SPLIT_DATE].copy()

# Create the test set: All data after the split date
test_df = df_temp[df_temp['FullDate'] >= SPLIT_DATE].copy()

# Removing the temporary 'FullDate' columns
train_df = train_df.drop("FullDate", axis=1)
test_df = test_df.drop("FullDate", axis=1)
df_temp = df_temp.drop("FullDate", axis=1)

len(train_df)+len(test_df)

73100

In [43]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 63800 entries, 0 to 63799
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Store ID            63800 non-null  category
 1   Product ID          63800 non-null  category
 2   Category            63800 non-null  category
 3   Region              63800 non-null  category
 4   Inventory Level     63800 non-null  int64
 5   Units Sold          63800 non-null  int64
 6   Units Ordered       63800 non-null  int64
 7   Demand Forecast     63800 non-null  float64
 8   Price               63800 non-null  float64
 9   Discount            63800 non-null  int64
 10  Weather Condition   63800 non-null  category
 11  Holiday/Promotion   63800 non-null  int64
 12  Competitor Pricing  63800 non-null  float64
 13  Seasonality         63800 non-null  category
 14  saleYear            63800 non-null  int32
 15  saleMonth           63800 non-null  int32
 16  saleDay             63800 non-null  int32
 17  dayOfWeek           63800 non-null  int32
 18  dayOfYear           63800 non-null  int32
dtypes: category(6), float64(3), int32(5), int64(5)
memory usage: 6.0 MB

In [48]:
# Define Target and Columns to Drop
TARGET_COLUMN = 'Units Sold'
# Drop processed columns and the target
COLUMNS_TO_DROP = [TARGET_COLUMN, 'Demand Forecast']

# Separate Features (X) and Target (y)
X_train = train_df.drop(columns=COLUMNS_TO_DROP)
y_train = train_df[TARGET_COLUMN]

X_test = test_df.drop(columns=COLUMNS_TO_DROP)
y_test = test_df[TARGET_COLUMN]

In [49]:
categorical_features = ['Store ID', 'Product ID', 'Category', 'Region', 
                        'Weather Condition', 'Seasonality']

# Apply One-Hot Encoding to both sets
X_train_encoded = pd.get_dummies(X_train, columns=categorical_features, drop_first=True)
X_test_encoded = pd.get_dummies(X_test, columns=categorical_features, drop_first=True)

# Align columns - CRITICAL STEP!
# The test set might not contain all categories present in the train set, 
# leading to a different number of columns. This aligns them, filling missing columns with 0.
X_train_cols = X_train_encoded.columns
X_test_encoded = X_test_encoded.reindex(columns=X_train_cols, fill_value=0)

In [50]:
# Initialize the Random Forest Regressor
rf_model = RandomForestRegressor(
    n_estimators=150,        # Use more trees for better performance
    max_depth=10,            # Limit tree depth to prevent overfitting
    min_samples_leaf=5,      # Ensure each leaf has at least 5 samples
    random_state=42,
    n_jobs=-1                # Use all CPU cores for speed
)

print("Starting Random Forest Model Training...")

# Train the model
rf_model.fit(X_train_encoded, y_train)

print("Training Complete. Making Predictions...")

# Make predictions on the test set
y_pred = rf_model.predict(X_test_encoded)

Starting Random Forest Model Training...
Training Complete. Making Predictions...

In [56]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
# Ensure predictions are non-negative (sales cannot be negative)
y_pred = np.maximum(0, y_pred)

# Calculate Evaluation Metrics
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
mae = mean_absolute_error(y_test, y_pred)

# Mean Absolute Percentage Error (MAPE) is key for demand forecasting
def calculate_mape(y_true, y_pred):
    # Avoid division by zero by replacing 0s with a small epsilon
    epsilon = 1e-10
    y_true_safe = np.where(y_true == 0, epsilon, y_true)
    return np.mean(np.abs((y_true - y_pred) / y_true_safe)) * 100

mape = calculate_mape(y_test, y_pred)

print("\n--- Random Forest Regression Performance ---")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"Mean Absolute Percentage Error (MAPE): {mape:.2f}%")

--- Random Forest Regression Performance ---
Root Mean Squared Error (RMSE): 88.09
Mean Absolute Error (MAE): 69.04
Mean Absolute Percentage Error (MAPE): 301570586811.70%